version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistemapos
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sistemapos
    ports:
      - '3001:3000'
    depends_on:
      - db
  web:
    build: ./apps/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - '3000:3000'
    depends_on:
      - api
volumes:
  postgres_data:
